version: "3.9"
services:

  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file: .env

  frontend:
    build: ./frontend
    container_name: star-burger-frontend
    restart: on-failure
    volumes: 
      - static:/opt/star-burger/static
      - media:/opt/star-burger/media

  backend:
    build: ./backend
    container_name: star-burger-backend
    depends_on:
      - db
      - frontend
    command: gunicorn -w 3 -p 8000 star_burger.wsgi
    restart: always
    env_file: .env
    expose:
      - 8000
    volumes: 
      - static:/opt/star-burger/static
      - media:/opt/star-burger/media

  nginx:
    build: ./nginx
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"
    volumes:
      - static:/opt/star-burger/static
      - media:/opt/star-burger/media

volumes:
  static:
  media:
  pg_data: