version: "3.9"
services:

  db:
    image: postgres:13-alpine
    container_name: star-burger-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file: .env

  frontend:
    build: ./frontend
    container_name: star-burger-frontend
    command: sh -c "./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./""
    restart: on-failure
    volumes: 
      - frontend:/opt/star-burger

  backend:
    build: ./backend
    container_name: star-burger-backend
    depends_on:
      - db
      - frontend
    command: bash -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn -w 3 --bind 0.0.0.0:8000 star_burger.wsgi"
    restart: always
    expose:
      - 8000
    volumes: 
      - static:/opt/star-burger/static
      - media:/opt/star-burger/media

  nginx:
    build: ./nginx
    container_name: star-burger-nginx
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"
    volumes:
      - frontend:/opt/star-burger/frontend
      - media:/opt/star-burger/media

volumes:
  frontend:
  static:
  media:
  pg_data: